# Generated by Django 3.2 on 2021-10-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211016_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('packed', 'packed'), ('on the way ', 'on the way'), ('delevered', 'delevered'), ('cancel', 'cancel')], default='pending', max_length=50),
        ),
    ]
