# Generated by Django 3.2 on 2021-10-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='total_price',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
